1. Import the numpy package under the name np (★☆☆)')

In [1]:
import  numpy as np


2. Print the numpy version and the configuration (★☆☆)') 打印numpy版本

In [4]:
print(np.__version__)

1.26.0


3. Create a null vector of size 10 (★☆☆)')  创建一个size为10的空向量

In [7]:
# np.empty 构造一个大小为 shape 的未初始化数组,
# np.zeros 构造一个大小为 shape 的全0数组,
# np.ones 构造一个大小为 shape 的全1数组,
print(np.zeros(10))
print(np.full((2,3),5.1))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[5.1 5.1 5.1]
 [5.1 5.1 5.1]]


    4、How to find the memory size of any array (★☆☆)')
    查看数组占用内存大小

In [7]:
Z = np.zeros((2,2))
print(Z.size*Z.itemsize)

32


5. How to get the documentation of the numpy add function from the command line? (★☆☆)')
查看numpy中add函数的用法

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)')
创建一个大小为10的空向量，将第5个值设为1

In [9]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7、Create a vector with values ranging from 10 to 49 (★☆☆)')
用10到49的序列构建一个向量

In [10]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)')
将一个数组变换倒序（最后一个元素成为第一个元素）

In [11]:
z = np.arange(5)
print(z[::-1])

[4 3 2 1 0]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)')
用0-8这9个数构造一个3x3大小的矩阵

In [16]:
# reshape 可以允许有一个参数为-1 ，系统会依据元素个数进行换算
Z = np.arange(9)
Z = Z.reshape((3,-1))
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)')
从数组[1,2,0,0,4,0]中找出非0元素的下标

In [17]:
# 直接就是一个函数的调用
print(np.nonzero([1, 2, 0, 0, 4, 0]))

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix (★☆☆)')
创建3x3的对角矩阵

In [22]:
# eye函数为对角线方阵函数   默认第一个和第二个参数相等，第三个参数为对角线位置
print(np.eye(3,3,0)) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)')
用随机数创建一个3x3x3的矩阵

In [2]:
print(np.random.random((3,3,3)))

[[[0.31063024 0.16740101 0.16669268]
  [0.09512781 0.08402649 0.3250009 ]
  [0.930577   0.86525312 0.84099957]]

 [[0.89457945 0.47284741 0.57024416]
  [0.95228752 0.20259826 0.54498983]
  [0.74699559 0.21953833 0.46896824]]

 [[0.49398834 0.31258144 0.75806161]
  [0.31387007 0.40162698 0.86246942]
  [0.10918903 0.10301681 0.27018636]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)')
创建一个10x10的随机数矩阵，并找到最大值和最小值

In [3]:
sample = np.random.random((10,10))
print(sample)
print(sample.max(),sample.min())

[[0.67403077 0.25994059 0.62286279 0.96833729 0.71525618 0.55518256
  0.57349266 0.78731826 0.55487533 0.2092418 ]
 [0.66770565 0.60108121 0.02554386 0.48812085 0.34496485 0.97350678
  0.53516662 0.0190299  0.37173883 0.04783323]
 [0.63429535 0.25044188 0.61078225 0.2036714  0.26429658 0.13194824
  0.40303132 0.30875163 0.39295226 0.16320092]
 [0.31264045 0.59725618 0.62977181 0.01426315 0.30403523 0.47865258
  0.46861153 0.47661143 0.20548856 0.07742402]
 [0.3699263  0.76245448 0.96777203 0.22685221 0.52891422 0.00620351
  0.24093106 0.05944034 0.90737393 0.30712716]
 [0.44121318 0.23617954 0.35055127 0.52263729 0.2532481  0.64732683
  0.99922873 0.79308998 0.23853628 0.87245781]
 [0.92388753 0.63046526 0.46100269 0.55639433 0.44192026 0.49753818
  0.71348076 0.48377329 0.12740372 0.92353087]
 [0.50724692 0.76461906 0.36909538 0.3750733  0.30754635 0.16232404
  0.2070471  0.92338493 0.87348127 0.95199187]
 [0.80419614 0.59323148 0.98082811 0.7128871  0.72650194 0.22456328
  0.07282892

14. Create a random vector of size 30 and find the mean value (★☆☆)')
创建一个大小为30的数组，并计算其算术平均值

In [4]:
print(np.random.random(30).mean())

0.47073934957690344


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
创建一个2d数组，边框为1，内部为0


In [5]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0s) around an existing array? (★☆☆)')
扩展给定数组的边界

In [5]:
sample16 = np.ones((4,4))
print(sample16)
print(np.pad(sample16, 1, mode='constant', constant_values=0))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆)')
指出下列表达式的结果是什么?

In [6]:
# nan的意思是Not a Number nan的类型是float64
print(0 * np.nan)  # nan  有nan参与的运算, 其结果也一定是nan
print(np.nan - np.nan) # nan
print(np.nan == np.nan) # False nan不是数，所以无法进行比较运算
print(np.nan > np.nan) # False
print(np.nan in {np.nan}) # True  nan在nan的字典中
print(0.3 == 3 * 0.1) # False  浮点数可以比大小，但相等要用math.isclose比较
import math
print(math.isclose(0.3, 3 * 0.1)) # True

nan
nan
False
False
True
False
True


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)')
用1，2，3，4做为对角线的下移一行，来创建5x5的矩阵

In [10]:
# hint diag函数的第二个参数指定对角线的位置
print(np.diag([1, 2, 3, 4], -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)')
创建一个类似国际象棋棋盘的8x8的矩阵

In [11]:
sample19 = np.zeros((8, 8))

sample19[::2, ::2] = 1
sample19[1::2, 1::2] = 1
print(sample19)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?(★☆☆)')
对一个6x7x8的数组，找出第100个元素的下标

In [14]:
#unravel_index方法 “一句话概括：求出数组某元素（或某组元素）拉成一维后的索引值在原本维度（或指定新维度）中对应的索引”
sample = np.zeros((6,7,8))
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)')
使用tile函数创建一个棋盘

In [17]:
# tile作用是 将A扩大倍数，其中（2,2）表示X轴扩大两倍，Y轴扩大两倍，以此类推。
print(np.tile([[0, 1], [1, 0]], (2, 2)))

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]
