In [1]:
import torch

1. 创建3x5的空张量

In [6]:
x = torch.empty(3,5)
x

tensor([[-5.0749e+30,  1.4714e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

2. 创建3X5随机张量

In [4]:
x = torch.rand(3,5)
x

tensor([[0.6091, 0.0371, 0.3580, 0.3495, 0.5368],
        [0.5691, 0.6622, 0.4659, 0.4967, 0.3460],
        [0.0990, 0.4412, 0.1128, 0.1115, 0.7850]])

3、创建3x5的 0 张量， 类型为long

In [2]:
x = torch.zeros(3,5,dtype=torch.long)
x

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

4、将数组转换为张量

In [3]:
lis = [5,4,3,1]
res = torch.tensor(lis)
res

tensor([5, 4, 3, 1])

5、创建一个3x5的单位张量，类型为double

In [4]:
x = torch.ones(3,5,dtype=torch.double)
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

6、返回一个与输入张量大小相同的张量，其中填充了均值为 0 方差为 1 的正态分布的随机值。且类型为double

In [5]:
x2 = torch.rand_like(x,dtype=torch.double)
x2

tensor([[0.8370, 0.2058, 0.0373, 0.7991, 0.4194],
        [0.7523, 0.5955, 0.4956, 0.0329, 0.5494],
        [0.4739, 0.0497, 0.8044, 0.6433, 0.7104]], dtype=torch.float64)

7、打印张量的维度

In [6]:
print(x2.size())

torch.Size([3, 5])


8、相加两个张量

In [7]:
a = [1,2]
b = [3,4]
a = torch.tensor(a)
b = torch.tensor(b)
print(a+b)

tensor([4, 6])


9、取tensor的第一列，注意 两种取法是不同的

In [9]:
x = torch.rand(3,5)
x

tensor([[0.3535, 0.6502, 0.8407, 0.3599, 0.5963],
        [0.8041, 0.3600, 0.0344, 0.9253, 0.3299],
        [0.3807, 0.3886, 0.0299, 0.9268, 0.1788]])

In [10]:
x[:,1]

tensor([0.6502, 0.3600, 0.3886])

In [11]:
x[:,0:1]

tensor([[0.3535],
        [0.8041],
        [0.3807]])

10、 将一个4x4 tensor resize成一个一维tensor 。可以用view也可以用reshape，涉及到连续与不连续问题，所以无脑用reshape即可。
    
tips: 确定一个维度，-1的维度会被自动计算

In [15]:
x = torch.rand(4,4)
x

tensor([[0.7372, 0.0522, 0.1516, 0.0276],
        [0.2510, 0.7111, 0.9016, 0.7040],
        [0.8484, 0.9016, 0.0571, 0.9852],
        [0.8587, 0.0436, 0.4506, 0.1940]])

In [17]:
y = x.reshape(-1,8)
y

tensor([[0.7372, 0.0522, 0.1516, 0.0276, 0.2510, 0.7111, 0.9016, 0.7040],
        [0.8484, 0.9016, 0.0571, 0.9852, 0.8587, 0.0436, 0.4506, 0.1940]])

11 、 从tensor中取出数字

In [18]:
x = torch.rand(2,3)
x

tensor([[0.6338, 0.6765, 0.0342],
        [0.0363, 0.3282, 0.7946]])

In [19]:
print(x[0,1].item())

0.6765420436859131


12、