In [1]:
import torch

1. 创建3x5的空张量

In [6]:
x = torch.empty(3,5)
x

tensor([[-5.0749e+30,  1.4714e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

2. 创建3X5随机张量

In [4]:
x = torch.rand(3,5)
x

tensor([[0.6091, 0.0371, 0.3580, 0.3495, 0.5368],
        [0.5691, 0.6622, 0.4659, 0.4967, 0.3460],
        [0.0990, 0.4412, 0.1128, 0.1115, 0.7850]])

3、创建3x5的 0 张量， 类型为long

In [2]:
x = torch.zeros(3,5,dtype=torch.long)
x

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

4、将数组转换为张量

In [3]:
lis = [5,4,3,1]
res = torch.tensor(lis)
res

tensor([5, 4, 3, 1])

5、创建一个3x5的单位张量，类型为double

In [4]:
x = torch.ones(3,5,dtype=torch.double)
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

6、返回一个与输入张量大小相同的张量，其中填充了均值为 0 方差为 1 的正态分布的随机值。且类型为double

In [5]:
x2 = torch.rand_like(x,dtype=torch.double)
x2

tensor([[0.8370, 0.2058, 0.0373, 0.7991, 0.4194],
        [0.7523, 0.5955, 0.4956, 0.0329, 0.5494],
        [0.4739, 0.0497, 0.8044, 0.6433, 0.7104]], dtype=torch.float64)

7、打印张量的维度

In [6]:
print(x2.size())

torch.Size([3, 5])


8、相加两个张量

In [7]:
a = [1,2]
b = [3,4]
a = torch.tensor(a)
b = torch.tensor(b)
print(a+b)

tensor([4, 6])


9、取tensor的第一列，注意 两种取法是不同的

In [9]:
x = torch.rand(3,5)
x

tensor([[0.3535, 0.6502, 0.8407, 0.3599, 0.5963],
        [0.8041, 0.3600, 0.0344, 0.9253, 0.3299],
        [0.3807, 0.3886, 0.0299, 0.9268, 0.1788]])

In [10]:
x[:,1]

tensor([0.6502, 0.3600, 0.3886])

In [11]:
x[:,0:1]

tensor([[0.3535],
        [0.8041],
        [0.3807]])

10、 将一个4x4 tensor resize成一个一维tensor 。可以用view也可以用reshape，涉及到连续与不连续问题，所以无脑用reshape即可。
    
tips: 确定一个维度，-1的维度会被自动计算

In [15]:
x = torch.rand(4,4)
x

tensor([[0.7372, 0.0522, 0.1516, 0.0276],
        [0.2510, 0.7111, 0.9016, 0.7040],
        [0.8484, 0.9016, 0.0571, 0.9852],
        [0.8587, 0.0436, 0.4506, 0.1940]])

In [17]:
y = x.reshape(-1,8)
y

tensor([[0.7372, 0.0522, 0.1516, 0.0276, 0.2510, 0.7111, 0.9016, 0.7040],
        [0.8484, 0.9016, 0.0571, 0.9852, 0.8587, 0.0436, 0.4506, 0.1940]])

11 、 从tensor中取出数字

In [18]:
x = torch.rand(2,3)
x

tensor([[0.6338, 0.6765, 0.0342],
        [0.0363, 0.3282, 0.7946]])

In [19]:
print(x[0,1].item())

0.6765420436859131


12、连接张量，在行和列分别连接.0代表行，1代表列

In [16]:
x = torch.randn(2, 3)
x

tensor([[ 0.2184, -2.3641,  1.3701],
        [ 0.5852,  0.4669, -0.8358]])

In [17]:
torch.cat((x, x, x), 0)

tensor([[ 0.2184, -2.3641,  1.3701],
        [ 0.5852,  0.4669, -0.8358],
        [ 0.2184, -2.3641,  1.3701],
        [ 0.5852,  0.4669, -0.8358],
        [ 0.2184, -2.3641,  1.3701],
        [ 0.5852,  0.4669, -0.8358]])

In [18]:
torch.cat((x, x, x), 1)

tensor([[ 0.2184, -2.3641,  1.3701,  0.2184, -2.3641,  1.3701,  0.2184, -2.3641,
          1.3701],
        [ 0.5852,  0.4669, -0.8358,  0.5852,  0.4669, -0.8358,  0.5852,  0.4669,
         -0.8358]])

## 自动微分

13、 新建tensor 设置require_grad=True,   requires_grad 表达的含义是，这一参数是否保留（或者说持有，即在前向传播完成后，是否在显存中记录这一参数的梯度，而非立即释放）梯度，等待优化器执行optim.step()更新参数。

In [4]:
x = torch.ones(3,2,requires_grad=True)
y = torch.ones(3,2)
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


14、 对上述requires_grad=True的张量进行加法，输出会有AddBackward0

In [5]:
z = x + 2
print(z)
print(z.grad_fn)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


15、在对上述的z进行乘法操作，输出就会MulBackward0

In [10]:
zz = z * 2
print(zz)
out = zz.mean()
print(out)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<MulBackward0>)
tensor(6., grad_fn=<MeanBackward0>)


16、对out进行反向传播  

In [11]:
out.backward()

17、打印梯度d(out)/dx ，   out=mean((x+2)*2)

In [14]:
print(x.grad)

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333],
        [0.3333, 0.3333]])


# 数据集相关

18、为自己的深度学习创建自定义数据集

In [19]:
import pandas as pd
from torch.utils.data import Dataset
import os
from torchvision.io import read_image


class MyData(Dataset):
    """
    Args:
        csv_file: 图像名及标签csv文件存放
        例如：tshirt1.jpg, 0
             tshirt2.jpg, 0
        img_dir：数据存放的路径
        transform: 是否对图像进行转换
        target_transform: 是否对图像进行转换
    """

    def __init__(self, csv_file, img_dir, transform=None, target_transform=None):
        self.img_labels = pd.read_csv(csv_file)
        self.img_dir = img_dir
        self.transform = transform
        self.target_transform = target_transform

    def __getitem__(self, item):
        # os.path.join用于拼接路径
        img_path = os.path.join(self.img_dir, self.img_labels.iloc[item, 0])
        image = read_image(img_path)
        label = self.img_labels.iloc[item, 1]
        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            label = self.target_transform(label)
        return image, label

    def __len__(self):
        return len(self.img_labels)

19、使用DataLoaders进行训练

In [ ]:
from torch.utils.data import DataLoader
train_csv_file = 'your train file'
train_img_dir = 'your train dir'
train_data = MyData(train_csv_file,train_img_dir)

test_csv_file = 'your train file'
test_img_dir = 'your train dir'
test_data = MyData(train_csv_file,train_img_dir)

train_dataloader = DataLoader(train_data,batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=64, shuffle=True)

20、 使用transform(在之前数据集的基础上)

In [ ]:
# 还记得18题我们自定义的数据集吗，其中包含参数transform 和 target transform，
# 我们可以 在构造数据及时就对其进行相应的转换
# 很简单  只需简单增加几行
from torchvision import transforms
import os
from torchvision.io import read_image


class MyData(Dataset):
    """
    Args:
        csv_file: 图像名及标签csv文件存放
        例如：tshirt1.jpg, 0
             tshirt2.jpg, 0
        img_dir：数据存放的路径
        transform: 是否对图像进行转换
        target_transform: 是否对图像进行转换
    """

    def __init__(self, csv_file, img_dir, transform=None, target_transform=None,img_size):
        self.img_labels = pd.read_csv(csv_file)
        self.img_dir = img_dir
        self.transform = transform
        self.target_transform = target_transform
        # transforms库中集成了很多方法，具体可见官方文档
        self.transforms = transforms.Compose([
            transforms.Resize((img_size, img_size)),
            transforms.RandomHorizontalFlip(p=0.5),
            transforms.ToTensor()
        ])

    def __getitem__(self, item):
        # os.path.join用于拼接路径
        img_path = os.path.join(self.img_dir, self.img_labels.iloc[item, 0])
        image = read_image(img_path)
        label = self.img_labels.iloc[item, 1]
        if self.transform:
            image = self.transforms(image)
        if self.target_transform:
            # 如果是分类任务当然用不到转换，但如果标签也是图像就可以用到了。
            label = self.transforms(label)
        return image, label

    def __len__(self):
        return len(self.img_labels)

## 构建神经网络

21、 定义一个简单的神经网络

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class MyNet(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 1 input image channel, 6 output channels, 5x5 square convolution
        self.conv1 = nn.Conv2d(1,6,5)
        
        
